version: '3.9'

services:
  #Mongodb Services
  mongo_db:
    container_name: techmec_db
    image: mongo:4.4
    restart: unless-stopped
    # restart: always
    ports:
      - 2717:27017
    volumes:
      - techmongovol:/data/db
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    networks:
      - backendnet

    #NodeJs Service
  nodeapp:
    container_name: "techmec_api"
    build: ./src/
    restart: unless-stopped
    ports:
      - 8888:8888
    depends_on:
      - mongo_db
    volumes:
      - technodevol:/var/app/src
    networks:
      - backendnet
      - frontendnet
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_KEY: ${JWT_KEY}
      MASTER_KEY: ${MASTER_KEY}
      RP_KeyId: ${RP_KeyId}
      RP_KeySecret: ${RP_KeySecret}
      EMAILID: ${EMAILID}
      EMAILPASS: ${EMAILPASS}
    # environment:
    #   DATABASE_URL: "mongodb://mongo_db:27017"
    #   PORT: 8888
    #   JWT_KEY: Uw!@7oL#Rk9X!3
    #   MASTER_KEY: p$$9Wu4!%h5ew8e
    #   RP_KeyId: rzp_test_tu7TRR4ScII9h3
    #   RP_KeySecret: t38HQMXXRKDUWAxNNr6HHKQt
    #   EMAILID: senseio.dev@gmail.com
    #   EMAILPASS: "@Q92*Q8@L&Bkum"
    # command: ./docker-entrypoint.sh mongo_db:27017 -- node server.js

  #Website Services
  webapp:
    container_name: "techmec_web"
    build: ./web/
    restart: unless-stopped
    # restart: always
    ports:
      - 80:80
    depends_on:
      - nodeapp
    networks:
      - frontendnet

volumes:
  techmongovol: {}
  technodevol: {}

networks:
  backendnet:
    driver: bridge
  frontendnet:
    driver: bridge